#!/usr/bin/env python3
import argparse
import os

import torch

import npfl138
npfl138.require_version("2526.8")
from npfl138.datasets.morpho_dataset import MorphoDataset

parser = argparse.ArgumentParser()
# These arguments will be set appropriately by ReCodEx, even if you change them.
parser.add_argument("--batch_size", default=10, type=int, help="Batch size.")
parser.add_argument("--epochs", default=5, type=int, help="Number of epochs.")
parser.add_argument("--max_sentences", default=None, type=int, help="Maximum number of sentences to load.")
parser.add_argument("--recodex", default=False, action="store_true", help="Evaluation in ReCodEx.")
parser.add_argument("--rnn", default="LSTM", choices=["LSTM", "GRU"], help="RNN layer type.")
parser.add_argument("--rnn_dim", default=64, type=int, help="RNN layer dimension.")
parser.add_argument("--seed", default=41, type=int, help="Random seed.")
parser.add_argument("--threads", default=1, type=int, help="Maximum number of threads to use.")
parser.add_argument("--we_dim", default=128, type=int, help="Word embedding dimension.")
# If you add more arguments, ReCodEx will keep them with your default values.


class Model(npfl138.TrainableModule):
    def __init__(self, args: argparse.Namespace, train: MorphoDataset.Dataset) -> None:
        super().__init__()
        self._rnn_dim = args.rnn_dim

        # Create all needed layers.
        # TODO(tagger_we): Create a `torch.nn.Embedding` layer, embedding the word ids
        # from `train.words.string_vocab` to dimensionality `args.we_dim`.
        self._word_embedding = torch.nn.Embedding(len(train.words.string_vocab), args.we_dim)

        # TODO(tagger_we): Create an RNN layer, either `torch.nn.LSTM` or `torch.nn.GRU` depending
        # on `args.rnn`. The layer should be bidirectional (`bidirectional=True`) with
        # dimensionality `args.rnn_dim`. During the model computation, the layer will
        # process the word embeddings generated by the `self._word_embedding` layer,
        # and we will sum the outputs of forward and backward directions.
        self._word_rnn = getattr(torch.nn, args.rnn)(
            args.we_dim, args.rnn_dim, batch_first=True, bidirectional=True,
        )

        # TODO(tagger_we): Create an output linear layer (`torch.nn.Linear`) processing the RNN output,
        # producing logits for tag prediction; `train.tags.string_vocab` is the tag vocabulary.
        self._output_layer = torch.nn.Linear(args.rnn_dim, len(train.tags.string_vocab))

    def forward(self, word_ids: torch.Tensor) -> torch.Tensor:
        # TODO(tagger_we): Start by embedding the `word_ids` using the word embedding layer.
        hidden = self._word_embedding(word_ids)

        # TODO(tagger_we): Process the embedded words through the RNN layer. Because the sentences
        # have different length, you have to use `torch.nn.utils.rnn.pack_padded_sequence`
        # to construct a variable-length `PackedSequence` from the input. You need to compute
        # the length of each sentence in the batch (by counting non-`MorphoDataset.PAD` tokens);
        # note that these lengths must be on CPU, so you might need to use the `.cpu()` method.
        # Finally, also pass `batch_first=True` and `enforce_sorted=False` to the call.
        lengths = (word_ids != MorphoDataset.PAD).sum(dim=1).cpu()
        packed = torch.nn.utils.rnn.pack_padded_sequence(
            hidden, lengths, batch_first=True, enforce_sorted=False,
        )

        # TODO(tagger_we): Pass the `PackedSequence` through the RNN, choosing the appropriate output.
        packed, _ = self._word_rnn(packed)

        # TODO(tagger_we): Unpack the RNN output using the `torch.nn.utils.rnn.pad_packed_sequence` with
        # `batch_first=True` argument. Then sum the outputs of forward and backward directions.
        hidden, _ = torch.nn.utils.rnn.pad_packed_sequence(packed, batch_first=True)
        hidden = hidden[:, :, :self._rnn_dim] + hidden[:, :, self._rnn_dim:]

        # TODO(tagger_we): Pass the RNN output through the output layer. Such an output has a shape
        # `[batch_size, sequence_length, num_tags]`, but the loss and the metric expect
        # the `num_tags` dimension to be in front (`[batch_size, num_tags, sequence_length]`),
        # so you need to reorder the dimensions.
        hidden = self._output_layer(hidden).permute(0, 2, 1)

        return hidden

    def compute_loss(self, y_pred: torch.Tensor, y_true: torch.Tensor, word_ids: torch.Tensor) -> torch.Tensor:
        # TODO: Compute the loss as the negative log-likelihood of the gold data `y_true`.
        # The computation must process the whole batch at once.
        # - Start by computing the log probabilities of the predictions using the `log_softmax` method.
        # - Compute the alphas according to the CTC algorithm.
        # - Then, you need to take the appropriate alpha for every batch example (using the corresponding
        #   lengths of `y_pred` and also `y_true`) and compute the loss from it.
        # - The losses of the individual examples should be divided by the length of the
        #   target sequence (excluding padding; use 1 if the target sequence is empty).
        #   - This is because we want to compute averages per logit; the `torch.nn.CTCLoss` does
        #     exactly the same when `reduction="mean"` (the default) is used.
        # - Finally, return the mean of the resulting losses.
        #
        # Several comments:
        # - You can add numbers represented in log space using `torch.logsumexp`/`torch.logaddexp`.
        # - With a slight abuse of notation, use `MorphoDataset.PAD` as the blank label in the CTC algorithm
        #   because `MorphoDataset.PAD` is never a valid output tag.
        # - During the computation, I use `-1e9` as the representation of negative infinity; using
        #   `-torch.inf` did not work for me because some operations were not well defined.
        # - During the loss computation, in some cases the target sequence cannot be produced at all.
        #   In that case return 0 as the loss (the same behaviour as passing `zero_infinity=True`
        #   to `torch.nn.CTCLoss`).
        # - During development, you can compare your outputs to the outputs of `torch.nn.CTCLoss`
        #   (with `reduction="none"` you can compare individual batch examples; in that case,
        #   the normalization by the target sequence lengths is not performed).  However, in ReCodEx,
        #   `torch.nn.CTCLoss` is not available.
        log_probs = y_pred.log_softmax(dim=1).permute(2, 0, 1)
        input_lengths = (word_ids != MorphoDataset.PAD).sum(dim=1)
        target_lengths = (y_true != MorphoDataset.PAD).sum(dim=1)

        batch_size, max_target_length = y_true.shape
        max_states = 2 * max_target_length + 1
        neg_inf = torch.tensor(-1e9, dtype=log_probs.dtype, device=log_probs.device)

        extended = torch.full(
            (batch_size, max_states), MorphoDataset.PAD, dtype=torch.long, device=y_true.device,
        )
        if max_target_length:
            extended[:, 1::2] = y_true

        state_indices = torch.arange(max_states, device=y_true.device)
        state_valid = state_indices.unsqueeze(0) <= (2 * target_lengths).unsqueeze(1)

        skip_allowed = torch.zeros_like(state_valid)
        if max_states > 2:
            skip_allowed[:, 2:] = (
                state_valid[:, 2:]
                & (extended[:, 2:] != MorphoDataset.PAD)
                & (extended[:, 2:] != extended[:, :-2])
            )

        emissions = log_probs[0].gather(1, extended)
        alpha = torch.full_like(emissions, neg_inf)
        alpha[:, 0] = emissions[:, 0]
        if max_states > 1:
            alpha[:, 1] = torch.where(
                target_lengths > 0, emissions[:, 1], torch.full_like(emissions[:, 1], neg_inf),
            )
        alpha = torch.where(state_valid, alpha, torch.full_like(alpha, neg_inf))

        history = [alpha]
        neg1 = torch.full((batch_size, 1), neg_inf, dtype=alpha.dtype, device=alpha.device)
        neg2 = torch.full((batch_size, 2), neg_inf, dtype=alpha.dtype, device=alpha.device)
        for t in range(1, log_probs.shape[0]):
            emissions = log_probs[t].gather(1, extended)
            stay = alpha
            move = torch.cat([neg1, alpha[:, :-1]], dim=1)
            total = torch.logaddexp(stay, move)
            if max_states > 2:
                skip = torch.cat([neg2, alpha[:, :-2]], dim=1)
                total = torch.where(skip_allowed, torch.logaddexp(total, skip), total)
            alpha = emissions + total
            alpha = torch.where(state_valid, alpha, torch.full_like(alpha, neg_inf))
            history.append(alpha)

        history = torch.stack(history)
        final_alpha = history[input_lengths - 1, torch.arange(batch_size, device=y_true.device)]

        last_blank = 2 * target_lengths
        final_blank = final_alpha.gather(1, last_blank.unsqueeze(1)).squeeze(1)
        if max_states > 1:
            last_label = torch.clamp(last_blank - 1, min=0)
            final_label = final_alpha.gather(1, last_label.unsqueeze(1)).squeeze(1)
            final_label = torch.where(
                target_lengths > 0, final_label, torch.full_like(final_label, neg_inf),
            )
            log_likelihood = torch.logaddexp(final_blank, final_label)
        else:
            log_likelihood = final_blank

        losses = -log_likelihood / target_lengths.clamp(min=1).to(log_likelihood.dtype)
        losses = torch.where(log_likelihood <= neg_inf / 2, torch.zeros_like(losses), losses)
        return losses.mean()

    def ctc_decoding(self, logits: torch.Tensor, word_ids: torch.Tensor) -> list[list[int]]:
        # TODO: Implement greedy CTC decoding algorithm. The result should be a list of
        # decoded tag sequences, each sequence (batch example) with appropriate length
        # (i.e., at this point we do not pad the predictions in the batch to the same length).
        #
        # The greedy algorithm should, for every batch example:
        # - consider only the predictions corresponding to valid words (i.e., not the padding ones);
        # - compute the most probable extended label for every one of them;
        # - remove repeated labels;
        # - finally remove the blank labels (which are `MorphoDataset.PAD` in our case).
        best_labels = logits.argmax(dim=1)
        lengths = (word_ids != MorphoDataset.PAD).sum(dim=1)
        predictions = []
        for labels, length in zip(best_labels, lengths):
            labels = labels[:length]
            if len(labels) == 0:
                predictions.append([])
                continue
            keep = torch.ones_like(labels, dtype=torch.bool)
            keep[1:] = labels[1:] != labels[:-1]
            labels = labels[keep]
            labels = labels[labels != MorphoDataset.PAD]
            predictions.append(labels.tolist())
        return predictions

    def compute_metrics(
        self, y_pred: torch.Tensor, y_true: torch.Tensor, word_ids: torch.Tensor
    ) -> dict[str, torch.Tensor]:
        # TODO: Compute predictions using the `ctc_decoding`.
        predictions = self.ctc_decoding(y_pred, word_ids)

        gold = [tags[tags != MorphoDataset.PAD].tolist() for tags in y_true]
        self.metrics["edit_distance"].update(predictions, gold)
        return self.metrics

    def predict_step(self, xs):
        with torch.no_grad():
            # Perform constrained decoding.
            yield from self.ctc_decoding(self.forward(*xs), *xs)


class TrainableDataset(npfl138.TransformedDataset):
    def transform(self, example):
        # TODO(tagger_we): Construct a single example, each consisting of the following pair:
        # - a PyTorch tensor of integer ids of input words as input,
        # - a PyTorch tensor of integer tag ids as targets.
        # To create the ids, use `string_vocab` of `self.dataset.words` and `self.dataset.tags`.
        #
        # TODO: However, compared to `tagger_we`, keep in the target sequence only the tags
        # starting with "B-" (before remapping them to ids).
        word_ids = torch.tensor(self.dataset.words.string_vocab.indices(example["words"]), dtype=torch.int64)
        tag_ids = torch.tensor(
            self.dataset.tags.string_vocab.indices([tag for tag in example["tags"] if tag.startswith("B-")]),
            dtype=torch.int64,
        )
        return word_ids, tag_ids

    def collate(self, batch):
        # Construct a single batch, where `batch` is a list of examples
        # generated by `transform`.
        word_ids, tag_ids = zip(*batch)
        # TODO(tagger_we): Combine `word_ids` into a single tensor, padding shorter
        # sequences to length of the longest sequence in the batch with zeros
        # using `torch.nn.utils.rnn.pad_sequence` with `batch_first=True` argument.
        word_ids = torch.nn.utils.rnn.pad_sequence(word_ids, batch_first=True, padding_value=MorphoDataset.PAD)
        # TODO(tagger_we): Process `tag_ids` analogously to `word_ids`.
        tag_ids = torch.nn.utils.rnn.pad_sequence(tag_ids, batch_first=True, padding_value=MorphoDataset.PAD)
        return word_ids, tag_ids


def main(args: argparse.Namespace) -> dict[str, float]:
    # Set the random seed and the number of threads.
    npfl138.startup(args.seed, args.threads)
    npfl138.global_keras_initializers()

    # Load the data.
    morpho = MorphoDataset("czech_cnec", max_sentences=args.max_sentences)

    # Prepare the data for training.
    train = TrainableDataset(morpho.train).dataloader(batch_size=args.batch_size, shuffle=True)
    dev = TrainableDataset(morpho.dev).dataloader(batch_size=args.batch_size)

    # Create the model and train.
    model = Model(args, morpho.train)

    model.configure(
        # TODO(tagger_we): Create the Adam optimizer.
        optimizer=torch.optim.Adam(model.parameters()),
        # We compute the loss using `compute_loss` method, so no `loss` is passed here.
        metrics={
            # TODO: Create `npfl138.metrics.EditDistance` evaluating CTC greedy decoding, passing
            # `ignore_index=morpho.PAD`.
            "edit_distance": npfl138.metrics.EditDistance(ignore_index=morpho.PAD),
        },
        logdir=npfl138.format_logdir("logs/{file-}{timestamp}{-config}", **vars(args)),
    )

    logs = model.fit(train, dev=dev, epochs=args.epochs)

    # Return all metrics for ReCodEx to validate.
    return {metric: value for metric, value in logs.items()}


if __name__ == "__main__":
    main_args = parser.parse_args([] if "__file__" not in globals() else None)
    main(main_args)
